### PR TITLE
[WIP] AC-413: SAML configuration

### PR DESCRIPTION
**Pull request by johnathana**

### CODE REVIEW

**Comment by andmarios** [comment]
@johnathana @deanlinaras can you please co-ordinate with @adamosloizou and change the SAML SSL option names?
There is a standard naming for SSL options and it's better to follow conventions rather than invent new option names. :sweat_smile: 

```
LENSES_SECURITY_SAML_KEYSTORE_PASSWORD → LENSES_SECURITY_SAML_SSL_KEYSTORE_PASSWORD
LENSES_SECURITY_SAML_KEYSTORE_KEY_PASSWORD → LENSES_SECURITY_SAML_SSL_KEY_PASSWORD
LENSES_SECURITY_SAML_KEYSTORE_LOCATION →
LENSES_SECURITY_SAML_SSL_KEYSTORE_LOCATION
```

**Review by andmarios — CHANGES_REQUESTED** [review]
Change option names in Lenses as in comment above.

**Comment by adamosloizou** [comment]
Hi @andmarios, thanks for the feedback.
These are not `SSL` options. They are crypto options used for the SAML crypto communications.
It's not related to SSL.
As such, do the names now perhaps make sense?

**Comment by andmarios** [comment]
Ah, I see! In such case I'll request only one change, to still be allied with keystore settings:
```
LENSES_SECURITY_SAML_KEYSTORE_KEY_PASSWORD → LENSES_SECURITY_SAML_KEY_PASSWORD
```

**Comment by johnathana** [comment]
> o still be allied with keystore settings:

This means the property **lenses.security.saml.keystore.key.password** should be renamed as **lenses.security.saml.key.password** on lenses backend.

**Comment by adamosloizou** [comment]
We can change that for `3.1` to make it consistent with the other keystore settings.
However, the more appropriate namespace is to put `key` under `keystore` because it's a _keystore key_ not any SAML key.
I will issue a PR now.
@andmarios you ok with changing this for `4.x` for all keystore related settings?

**Pull request closed without merging**
